jobs:
  test:
    runs-on: ubuntu-latest
    environment: release
    name: Test
    steps:
      - name: setup repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "npm"
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
name: Test, build and release
on:
  push:
    branches:
      - main
